# base image
FROM alpine
MAINTAINER Matt McCabe

# install python3
RUN add python3

# directory in which hello program resides
WORKDIR /MyDockerDir

# command to run within directory (ie run hello program)
CMD ["hello"]

# I don't actually know what this means but ill figure out later
EXPOSE 5000
